historical_steps: 50
future_steps: 50
num_modes: 6
rotate: true
node_dim: 2
edge_dim: 2
embed_dim: 64
num_heads: 8
dropout: 0.1
num_temporal_layers: 4
num_global_layers: 3
local_radius: 50
parallel: false
lr: 0.0005
weight_decay: 0.0001
T_max: 64
root: /home/yc27979/mc451742/V2I_trajectory_prediction/V2X-Seq/V2X-Seq-TFD/V2X-Seq-TFD/cooperative-vehicle-infrastructure
ckpt_path: ''
train_batch_size: 4
val_batch_size: 4
shuffle: true
num_workers: 4
pin_memory: true
persistent_workers: true
gpus: 2
max_epochs: 64
monitor: val_minFDE
save_top_k: 6
accelerator: gpu
accu_batch: 4
check_val_every_n_epoch: 5
